print("merhaba sayı oyunumuza hoş geldiniz")
print("aklından 1 ile 10 arasında bir sayı tut")
print("tuttun mu ?")
input()
print("tuttuğun sayıyı 2 ile çarp")
print("çarptın mı ?")
input()
print("çıkan sonuca 20 ekle")
print("ekledin mi ?")
input()
print("çıkan sonucu 2 ile böl")
print("böldün mü?")
input()
print("çıkan sonuçtan tuttuğun sayıyı çıkart")
print("çıkarttın mı?")
input()
print("sonucu duymaya hazır mısın ?")
input()
print("işlemlerinin sonucu : ",10)
